spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: mysql_user
    password: 123456
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true
      hibernate.order_updates: true
  h2:
    console:
      enabled: false

server:
  port: 8090
